name: Compare locales

on: [push, pull_request]

jobs:
  compare_locales:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: npm

      - run: npm ci

      - run: npm run i18n:compare-locales locales/en/common.json locales/es/common.json
      - run: npm run i18n:compare-locales locales/en/applications.json locales/es/applications.json
      - run: npm run i18n:compare-locales locales/en/jobs.json locales/es/jobs.json
      - run: npm run i18n:compare-locales locales/en/contracts.json locales/es/contracts.json

      - run: npm run i18n:compare-locales locales/en/common.json locales/pt/common.json
      - run: npm run i18n:compare-locales locales/en/applications.json locales/pt/applications.json
      - run: npm run i18n:compare-locales locales/en/jobs.json locales/pt/jobs.json
      - run: npm run i18n:compare-locales locales/en/contracts.json locales/pt/contracts.json
