name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

      - name: Prepare .env.local
        run: cp .env.local.example .env.local

      - name: Build the Docker image
        run: make build
